### ISSUE TITLE
errors when dungeon gets generated

### ISSUE THREAD

**Issue by V-Boy** [srwaggon/minecraft-roguelike#14]
https://paste.dimdev.org/eluwihatuc.md

**Comment by srwaggon** [comment]
This appears to have been an issue from partial dungeon definitions being generated as full dungeons. This issue also created "empty" dungeons, and seems to have been resolved by not allowing "empty" or partial dungeon definitions from being used to generate a "complete" dungeon.

Fixed in release [`v2.12.2`](https://github.com/srwaggon/minecraft-roguelike/releases/tag/v2.1.2)
